version: 2
jobs:
  build:
    docker:
      - image: ryanfrohar/broken-arm:v1.0
    steps:
      - checkout
      - run: 
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
